### ISSUE TITLE
Remove `alert` and `trigger` from the yaml

### ISSUE THREAD

**Issue by basepi** [HubbleStack/Nova#100]
Right now we've been adding a generic `alert` and `trigger` field to every audit check in the YAML. We should remove them. Once we implement the alert/trigger behavior, we don't want every state alerting/triggering. (Plus, these settings are currently set to garbage values)

Should go through all non-sample yaml files and remove `alert` and `trigger`.

**Comment by gmiu** [comment]
I can take care of this.

**Comment by basepi** [comment]
Thanks @avb76!

**Comment by gmiu** [comment]
Fixed in #103
