### ISSUE TITLE
Firewall Rule Audits

### ISSUE THREAD

**Issue by grimamethyst** [HubbleStack/Nova#118]
As part of PCI compliance, regular reviews of all prod firewalls are required.  However, this usually involves spending time going through the entire config file for each firewall.  That format is also generally impossible to hand off to auditors without copying out each individual rule from the config file.  Could the firewall tool built into Hubble include a feature that would pull in the rules and output them in a more organized, readable fashion?

**Comment by basepi** [comment]
I think this is doable, but will be low on the priority list for now.

**Comment by basepi** [comment]
This issue was moved to hubblestack/hubble-salt#50
