### ISSUE TITLE
PF firewall support

### ISSUE THREAD

**Issue by grimamethyst** [HubbleStack/Nova#119]
Extend the existing firewall module to support PF (versus creating a separate module).

**Comment by gmiu** [comment]
@grimamethyst, it looks like there is no salt execution module for `pf`.

Do you know if there is a `pf` command that checks the existence of a rule given as parameter? I'm leaving `grep` over `pf.conf` as a last solution. I don't have any experience with `pf`, but I guess a rule that does a certain thing might come under different formats, so `grep` wouldn't work that well. Please, correct me if I'm wrong.

**Comment by cedwards** [comment]
If there is no existing `pf` execution module, perhaps we should put that first. I realize that will be a bigger project, but we also don't need this _right_ away.

**Comment by basepi** [comment]
This issue was moved to hubblestack/hubble-salt#51
