### ISSUE TITLE
Standardize on lower-case profile names?

### ISSUE THREAD

**Issue by basepi** [HubbleStack/Nova#125]
I don't like the case sensitivity of our profiles right now. I'm thinking we standardize on lower-case.

cis-rhel-6-l1-scored.yaml

Thoughts? The current version is so easy to typo.

**Comment by gmiu** [comment]
+1 (I hate typing caps)

**Comment by cedwards** [comment]
Do it.

**Comment by SaltyCharles** [comment]
I'm checking but there may be some constraints on Windows (although we can make exceptions as needed for these).

**Comment by basepi** [comment]
windows is case-insensitive, isn't is? Keep us posted if you run into any problems, but I don't expect there to be any.
