### ISSUE TITLE
grep module whitelist returns failure when a file does not exist

### ISSUE THREAD

**Issue by dgmorrisjr** [HubbleStack/Nova#127]
Technically, i think there is no error in the current module...because if a file doesn't exist, then the line you are looking for can't be there.  

But from a business logic / compliance perspective there is an issue here.

For instance, If a package is NOT installed, then the configuration file should not be present.  If it's not present, then no need to inspect the file.

But if the package is installed, the configuration file "should" be present, and when grep'ing the file, ensure that a configuration is present.

Example: when `/etc/xinetd.d/tftp` is present, ensure that the server_args statement includes the `-s` statement (e.g. `server_args = -s /var/lib/tftpboot`).  

Therefore, "Success" situations:
1. The `/etc/xinetd.d/tftp` file is not present
2. But if present, the `-s` flag is in the `server_args` statement

"Failure" situations:
1. the `/etc/xinetd.d/tftp` file is present and the `-s` flag is NOT present in the `server_args` statement

I was thinking about how to do this as a blacklist check, but the `match_output` option doesn't execute a second grep (or at least I don't think that's what it's doing based on looking at the `grep.py` file - but again... i'm just now learning python... so could just be my lack of understanding)

**Comment by gmiu** [comment]
I confirm that `match_ouput` does not call another greping. The plugin seems to do well if a file that does not exist is checked in the blacklist. But, I don't think understand all the aspects of your problem :)

**Comment by dgmorrisjr** [comment]
in the situation i described above, the STIG (similar to a CIS control) is looking for the `-s` flag in the `server_args` line.

Creating this check in the whitelist for grep works great **IF** the file exists.  Which is the #2 Success situations I described above.  In this case the targeted server is compliant.

In Situation #1, if tftp is NOT installed, then the `/etc/xinetd.d/tftp` will not exist.  In this case, if we add the check above to the whitelist section, then it's returned as a "Failure".  when infact, the server is in compliance.

**Comment by dgmorrisjr** [comment]
just in case, here is the link to the STIG Control:
https://www.stigviewer.com/stig/red_hat_enterprise_linux_6/2015-05-26/finding/V-38701

**Comment by gmiu** [comment]
Just to be clear, from what you're saying, I understand that the system is compliant only if one of the following:
- `tftp` is not installed
- `tftp` is installed and `-s` option is set in the config file.

**Comment by dgmorrisjr** [comment]
correct.

**Comment by gmiu** [comment]
Maybe adding a `does_not_match_output` might solve the solution. But it depends on how generic are this kind of checks. In the end, adding the new option shoudn't be bad. If it's there, god. If it's not, better :) Maybe @cedwards or @basepi have other solutions for this kind of checks.

**Comment by basepi** [comment]
Maybe just a `success_on_file_missing` flag or something?

**Comment by dgmorrisjr** [comment]
sure that would work
