### ISSUE TITLE
grep module match_output should support listing multiple values or using grep for the output

### ISSUE THREAD

**Issue by dgmorrisjr** [HubbleStack/Nova#128]
Example:  in `sshd_config`, consider the parameter `PermitEmptyPasswords`.

The possible values for this could be `No` or `no` or `Yes` or `yes`.   

when doing an inspection as a blacklist, i want to ensure that this parameter is either commented out, not present, or does not contain either `Yes` or `yes`

if I configure the check in the following way:

```
        - /etc/ssh/sshd_config:
            pattern:      '^PermitEmptyPasswords'
            match_output: "yes"
            tag:          V-38614
```

it will pass if the actual value is `yes` but will fail if the actual value is `Yes`.

I currently have it configured in the following manner:

```
        - /etc/ssh/sshd_config:
            pattern:      '^PermitEmptyPasswords'
            match_output: "yes"
            tag:          V-38614
        - /etc/ssh/sshd_config:
            pattern:      '^PermitEmptyPasswords'
            match_output: "Yes"
            tag:          V-38614
```

But the problem here is that, while it will help be catch both failure possibilities, it still returns unnecessary  success results.

**Comment by gmiu** [comment]
For multiple variations on `yes`/`no`/other cases, it shouldn't be hard to modify the `grep` audit to support a list for `match_output`. The hard pard is dealing with commented lines I guess: we'd have to know all the syntaxes of the config files to be checked in order to know which character is used for commenting. It's not `#` in all config languages. After defining a list of commenting characters, it's easy to check if the is commented or not.

Also, I'm wondering if this is not a thing for the compliances documents to specify.

**Comment by dgmorrisjr** [comment]
The check i'm running here is in the blacklist section, i got to thinking about just specifying the options directly in the pattern section as well... so I tried this:

```
        - /etc/ssh/sshd_config:
            pattern:      '^PermitEmptyPasswords\s+(yes|Yes)'
            tag:          V-38614
```

When the value in my `sshd_config` file is this: 

```
[root@managernode ssh]# grep ^PermitEmptyPasswords sshd_config
PermitEmptyPasswords Yes
```

Here is my output from hubble:

```
[root@managernode ssh]# salt \manager hubble.audit stig-rhel6-mac1-classifed V-38614
manager:
    ----------
    Compliance:
        100%
    Controlled:
    Failure:
    Success:
        |_
          ----------
          description:
              (HIGH) The SSH daemon must not allow authentication using an empty password.
          module:
              grep
          name:
              /etc/ssh/sshd_config
          pattern:
              ^PermitEmptyPasswords\s+(yes|Yes)
          tag:
              V-38614
          type:
              blacklist
```

**Comment by dgmorrisjr** [comment]
@avb76 I agree with you on the comments in the config file.  For this reason, in the pattern statement, in the case for `sshd_config`, i use a beginning of line anchor `^` which causes the search to ignore the commented lines.  I tested multiple scenerios with the various checks i've tried above:

`PermitEmptyPasswords no`
`PermitEmptyPasswords No`
`PermitEmptyPasswords Yes`
`PermitEmptyPasswords yes`
`#PermitEmptyPasswords no`

using the `^` anchor causes the `#PermitEmptyPasswords` variation to be ignored

Another issue to consider:    with grep, would be good to be able to pass kwargs as well.   e.g. the `-i`   in that case, this wouldn't be an issue.  Further, I think that sshd_config can use upper or lower case versions of the parameters: e.g. `PermitEmptyPasswords` or `permitemptypasswords` or `PERMITEMPTYPASSWORDS` and sshd would work fine.   Therefore, from a compliance check, how do we better support these various situations?

**Comment by gmiu** [comment]
We use the `file.grep` salt module. Have you tried `salt-call file.grep /etc/ssh/sshd_config '^PermitEmptyPasswords\s+(yes|Yes)'` on that system?

Later edit: I put the pattern inside quotes.

**Comment by gmiu** [comment]
And regarding the commented lines, I forgot about the `^` at the beginning of the pattern :)

**Comment by dgmorrisjr** [comment]
I did look inside the python module and saw that... but after you mentioned it, I went ahead and tried many variations trying to get the `file.grep` module to work the way you'd expect...   but I think this example really helps illustrate something:

```
[root@managernode ssh]# grep -E '^PermitEmptyPasswords\s*(yes|Yes)' /etc/ssh/sshd_config
PermitEmptyPasswords yes
```

When I run grep -E it works as you'd expect.

However, when doing the same thing using the `file.grep` module, I tried to use the `-E` kwarg for `file.grep`, and the output error'd out:

```
[root@managernode ssh]# salt-call file.grep /etc/ssh/sshd_config "^PermitEmptyPasswords\s*(yes|Yes)" " -E"
[INFO    ] Executing command 'grep  -E ^PermitEmptyPasswords\\s*(yes|Yes) /etc/ssh/sshd_config' in directory '/root'
[ERROR   ] Command 'grep  -E ^PermitEmptyPasswords\\s*(yes|Yes) /etc/ssh/sshd_config' failed with return code: 1
[ERROR   ] retcode: 1
local:
    ----------
    pid:
        1853
    retcode:
        1
    stderr:
    stdout:
```

notice on my command line, I have the grep pattern correct, but int he command that `file.grep` tried to execute it has a `\\s*` so I think that is causing issues.

**Comment by gmiu** [comment]
@dgmorrisjr, after looking a bit over how `file.grep` salt module works, this is the correct way to search for that regex:

```
# salt-call file.grep /etc/ssh/sshd_config '"^PermitEmptyPasswords\s+(yes|Yes)"' -- '-E'
[INFO    ] Executing command 'grep  -E "^PermitEmptyPasswords\\s+(yes|Yes)" /etc/ssh/sshd_config' in directory '/root'
local:
    ----------
    pid:
        28454
    retcode:
        0
    stderr:
    stdout:
        PermitEmptyPasswords Yes
```

You have to pass the `-E` option in order to support regular expressions. We just use `file.grep` with no options.

And to answer your question, I think is best to use a list for `match_ouput`. Kwargs require some extra work in `hubble.py`. Using lists, we have to modify only 2, maybe 3 lines `grep.py`.

**Comment by dgmorrisjr** [comment]
I'm good with a list as well at the moment. Not sure yet if i'll come up with other use cases where a list in the `match_output` wouldn't work.

**Comment by gmiu** [comment]
I used single quotes over doubles quotes. Also, from there usage examples, you'd have to use `--` before passing the option.

**Comment by dgmorrisjr** [comment]
yeah - i saw the `--` in your example, but when looking at the documentation here:
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.file.html#salt.modules.file.grep

I didn't see anything that indicated the `--`.  good to know - Thanks!

**Comment by gmiu** [comment]
```
# salt-call file.grep /etc/ssh/sshd_config '"^PermitEmptyPasswords\s+(yes|Yes)"' ' -E'
[INFO    ] Executing command 'grep  -E "^PermitEmptyPasswords\\s+(yes|Yes)" /etc/ssh/sshd_config' in directory '/root'
local:
    ----------
    pid:
        29084
    retcode:
        0
    stderr:
    stdout:
        PermitEmptyPasswords Yes
```

Looks like this goes in your way too. I looked in the docstring from the code of `file.grep`. This iss odd: usually, that docstrings in functions match the ones in the web docs.

**Comment by dgmorrisjr** [comment]
super - thanks!

**Comment by gmiu** [comment]
Your problem was with the pattern. If you use only one set of quotes, the module read the whole pattern as one string, but it will pass the string without any quotes to the `grep` call inside `file.grep`. If you'll look inside the code, `cmd.run` is used to call `grep`. So, any special char will not be escaped.

**Comment by gmiu** [comment]
Regarding `match_output` as a list, we might want to hear another opinion from @basepi since he wrote designed `grep.py`.

**Comment by gmiu** [comment]
I think a new optional parameter in the profile check would do better for this: `case_sensitive: False`. When the plugin sees this, it would use `file.grep` with the `-i` flag.

**Comment by basepi** [comment]
Sounds like https://github.com/HubbleStack/Nova/issues/55 might resolve this. Is that correct?

It would also be pretty trivial to allow for regex on the match_output piece.

**Comment by dgmorrisjr** [comment]
I'm excited to try this out next time i get a chance to work on the STIG profiles!
