### ISSUE TITLE
Improve openscap module return structure

### ISSUE THREAD

**Issue by basepi** [HubbleStack/Nova#131]
We should split out the failures/successes from openscap properly so that we can compute compliance percentage better, and report successes if desired. We also want to organize the data by tag (CVE number?) so that we can control on those checks.

@cedwards Any other thoughts here?

**Comment by cedwards** [comment]
This is a good start. I'd like to do more, ie; #97, but this is a step in the right direction.

**Comment by basepi** [comment]
I may move on to #97 if I have time. I want to improve the basic reporting first.

**Comment by cedwards** [comment]
Should we close this as deprecated in favor of the new v2 scanner?

**Comment by basepi** [comment]
Probably reasonable.
