### ISSUE TITLE
Broader Coordination on DevSecOps ongoings

### ISSUE THREAD

**Issue by JJediny** [HubbleStack/Nova#152]
Really interested in this project as we are move towards salt, but would really like to know how it forsees itself aligning to other similar efforts around automated DevSecOp efforts:
- https://github.com/GovReady
- https://github.com/DevSecOps
- https://github.com/opencontrol

**Comment by basepi** [comment]
I haven't had a chance to look in depth at those projects, but I anticipate we should be able to integrate if desired. We should be able to leverage any existing project using a new nova module.

**Comment by basepi** [comment]
This issue was moved to hubblestack/hubble-salt#35
