### ISSUE TITLE
Update cve_scan2 to support salt fileserver

### ISSUE THREAD

**Issue by basepi** [HubbleStack/Nova#155]
Should support pulling data from `salt://` in addition to from the internet. Should be a pretty simple addition.

**Comment by dgmorrisjr** [comment]
Perfect - thanks!

**Comment by cedwards** [comment]
@jaredhanson11 please confirm that this is complete and close.

**Comment by jaredhanson11** [comment]
The merge of cve_scan_v2 today will support `salt://` urls as a source of cve data.
