### ISSUE TITLE
Nova schedule documentation

### ISSUE THREAD

**Issue by cedwards** [HubbleStack/Nova#215]
The README now includes a section on scheduling Nova audits. Is any returner information required to send this data somewhere useful? What would that syntax look like in full?

**Comment by basepi** [comment]
Oh, right, I totally forgot returners. I also found `return_job: False` in the scheduler docs, which will be a very useful setting. We need to make sure `return_job: False` doesn't disable an explicit `returner:` setting.

**Comment by basepi** [comment]
Done in #224. Tested and working.
