### ISSUE TITLE
Suggest of using Vulners Linux Audit API

### ISSUE THREAD

**Issue by vulnersCom** [HubbleStack/Nova#255]
Hi!
Thanks for using our DB, at first.
We release Linux Audit API and it will be very cool, if you will add it :)

It provides API for vulnerability scan.
As input it takes "rpm -qa" for RPM based systems and "dpkg-query -W -f='${Package} ${Version} ${Architecture}\n'" for Debian family.

GUI is here: https://vulners.com/#audit
Description here: https://blog.vulners.com/linux-vulnerability-audit-in-vulners/
And sample here with OS version detection: https://github.com/videns/vulners-scanner

It's extremely fast (~160ms) for checking 500-600 packages.
Hope, it will be usefull.

**Comment by basepi** [comment]
Very cool! We'll look into getting it added.

**Comment by vulnersCom** [comment]
Hello, fellows!
We see a lot of  /api/v3/archive/distributive/ calls at our serverside.
So, just as gentle reminder, maybe we will switch to much more traffic economy /api/v3/audit API? :)

**Comment by basepi** [comment]
Hehe, thanks for the reminder @vulnersCom. We definitely need to do that. Sorry for the increased traffic! :)

**Comment by vulnersCom** [comment]
No a problem)) We are glad to be useful))
If there will be any issues with audit API feel free to ask me.

**Comment by vulnersCom** [comment]
Hi, guys! Any help maybe ?)

**Comment by gmiu** [comment]
@vulnersCom, I will take a look over this during the next period! Maybe then :)

**Comment by vulnersCom** [comment]
Gentle Ping :)

**Comment by basepi** [comment]
This issue was moved to hubblestack/hubble-salt#54
