### ISSUE TITLE
For a win_reg failure, add the actual value to the verbose output

### ISSUE THREAD

**Issue by basepi** [HubbleStack/Nova#265]
We were trying to debug a win_reg failure, and realized that it would be really nice if the module stuck the actual value it found into the verbose output. That way we wouldn't have to dive into the registry ourselves to see why it didn't match.

@anuragpaliwal80

**Comment by madchills** [comment]
Submitted fix that will give you the value (found_value) when running verbose mode

**Comment by basepi** [comment]
Sweet! I merged it.
