### ISSUE TITLE
Compliance scanning for cloud providers

### ISSUE THREAD

**Issue by lorengordon** [HubbleStack/Nova#282]
Would be awesome if we could use hubblestack to scan for compliance against cloud provider benchmarks, such as this one, https://aws.amazon.com/blogs/security/tag/cis-aws-foundations-benchmark/

**Comment by basepi** [comment]
This would be great! Thanks for the request!

**Comment by basepi** [comment]
This issue was moved to hubblestack/hubble-salt#45
