### ISSUE TITLE
Missing CIS checks

### ISSUE THREAD

**Issue by mew1033** [HubbleStack/Nova#283]
centos-6-level-1-scored-v2-0-1.yaml is missing a few checks:

- [x] 5.2.12
- [x] 5.2.14
- [ ] 5.2.15

Possibly more, but that's what I've found.

**Comment by mew1033** [comment]
PR #284 adds in 5.2.12 and 5.2.14

**Comment by basepi** [comment]
Perfect. I modified the original issue with a checklist.

**Comment by basepi** [comment]
This issue was moved to hubblestack/hubble-salt#46
