### ISSUE TITLE
CIS CentOS 7 - 6.2.11

### ISSUE THREAD

**Issue by ssoto2** [HubbleStack/Nova#285]
In the centos-7-level-1-scored-v1.yaml 

6.2.11 is looking for the following: 

```
  sshd_approved_cipher:
      data:
        CentOS Linux-7:
        - /etc/ssh/sshd_config:
            match_output: 'Ciphers aes128-ctr,aes192-ctr,aes256-ctr '
            pattern: Ciphers
            tag: CIS-6.2.11
```

The addition space at the end of the match output is causing test to fail unless your sshd config had a space at the very end also.

**Comment by basepi** [comment]
Good catch! I'll fix that shortly.
