### ISSUE TITLE
running salt \* hubble.sync multiple times displays multiple times the file list

### ISSUE THREAD

**Issue by arthurzenika** [HubbleStack/Nova#293]
When running hubble.sync one can see the list of files synced with the minion. I am a bit surprised to see the same list when running it twice in a row. All the sync commands in salt will display only new files being synced. Does that mean all files are copied every time ? or just that the display does not show only new files ?

**Comment by basepi** [comment]
`cp.cache_dir` returns all files that are cached in that directory, not just new files, and we clean up this list a little bit (trimming cachedir information) and then return it as it is.

**Comment by basepi** [comment]
I think I answered your question, but feel free to continue discussing and I can re-open this issue if necessary.
