### ISSUE TITLE
certificate validation & expiry audit module

### ISSUE THREAD

**Issue by cedwards** [HubbleStack/Nova#38]
I'd like to see a module that would read SSL endpoints from the YAML profile and scan them for validity, expiration, etc. This would likely just require an ssl.py (or similar) and a YAML syntax for defining checks.

**Comment by gmiu** [comment]
@cedwards, we spoke about this and we've settled for a runner that does the ssl checks. But, thinking on how to implement this, the next question popped into my mind:

Should we create a separate runner just for ssl checks or should we create a runner similar to the `hubble` module, that receives different plugins (in this case, the plugin for ssl)? The second case might be useful if we'll have more runners for different checks in the future. 

Also, @basepi, what do you think?

**Comment by gmiu** [comment]
And btw, I have a sample for the ssl yaml:

```
ssl:
  google:
    endpoint: 'www.google.com'  # or null if file is defined
    file: null                  # /path/to/the/pem/file if endpoint is null
    port: 443                   # or null if endpoint is null
    warning: 10                 # number of days until expiration to get a warning
    critical: 5                 # number of days until expiration to get a critical warning
```

What do you think about this?

**Comment by gmiu** [comment]
Initial work for this finished in #151

**Comment by basepi** [comment]
Closing since this is finished.
