### ISSUE TITLE
hubblestack_nova directory structure design

### ISSUE THREAD

**Issue by cedwards** [HubbleStack/Nova#47]
Wanted to put some more thought and discussion into the directory structure of the `hubblestack_nova` folder. Should we organize sub-directories by module (so that we can include a rendered README)? Should profiles be collected into sub-directories for organization? etc.

**Comment by dgmorrisjr** [comment]
I do think directories would be helpful.  if the .py and .yaml files are all specific to one distribution (e.g. CentOS Linux-7), then grouping them by distro would be very useful.  What's a little confusing right now is having the CIS.yaml file and the pkg.yaml file.  They both have top-level 'pkg' keys.  If they have a different or conflicting whitelist or blacklist of files (e.g. pkgA in the whitelist for pkg.yaml, but in the blacklist for CIS.yaml), which file takes precedence?

**Comment by gmiu** [comment]
@dgmorrisjr, `pkg.py` will search for the `pkg` top-level key in each yaml file found in the `hubblestack_nova` directory and it will merge all the data in a single dictionary.

For a better understanding of the process, see `_get_yaml` and `_merge_yaml` functions. You can find them in any of the nova plugins.

**Comment by dgmorrisjr** [comment]
Thinking about this more after editing the CIS.yaml file for a bit.   Many organizations have their systems/servers designated with criticality levels based on the sensitivity of the information they contain/process.  As a result of this, a low-sensitivity set of hosts (e.g. user workstations) may need to be scanned against one profile (e.g. CIS-low.yaml), wheres a high-sensitivity set of hosts (e.g. Servers that support PCI, HIPPA, or R&D info/processes) may need to be scanned against a different profile (e.g. CIS-high.yaml).   

Another instance of this is when using the DISA STIGS.  They evaluate controls associated with Confidentiality, Integrity, and Availability.  Within each of these three categories, they have three criticality levels: High, Medium, and Low.   Systems are then rated with their criticality for each control group, for instance, a HML system, would be High Confidentiality, Medium Integrity, and Low Availability.   Each of the criticality levels specifies a different set of "baseline controls".   Therefore, one system in an enterprise may be categorized as a HMM system, whereas another system within the enterprise might be MML.  Lastly, in addition to these differing levels of baseline controls, NIST 800-53 also provides for "control overlays" which allows for further hardening/strengthening of special purpose systems.  For example, they have control overlays for systems that process PII (Personally Identifiable Information) and other categories of special purpose systems.

To accommodate this, we may need to have profiles that follow a structure such as:
- stig_conf_high.yaml
- stig_conf_medium.yaml
- stig_conf_low.yaml
- stig_integrity_high.yaml
- stig_integrity_medium.yaml
- stig_integrity_low.yaml
- stig_avail_high.yaml
- stig_avail_medium.yaml
- stig_avail_low.yaml

Then we can create sub-folders that are arbitrarily named to allow each enterprise to tailor to their environment (e.g. stig-hmm), then copy the appropriate C, I, and A set of files into the sub-folder.  If there are any other additional controls for that system(s), they can be added to the folder as well.  

Then, if at the `hubble.nova` command line, if we could have an argument such as `subfolder=stig-hmm` this would instruct the `hubble.nova` to restrict the import of `.yaml` files to the named sub-folder.   

I did review the `_merge_yaml` function, and admittedly, i'm just starting to learn python... so it's not apparent to me how the code logic handles when more than one tagged inspection exists for the same thing (e.g. two grep entries tagged with 'CIS-1.2.3', that have different patterns defined).

The last question that I would have here is regarding the `.py` files in the `hubblestack-nova` folder.  if there were to be multiple sub-folders for the various `.yaml` profiles, would there just be one set of `.py` files that live in the top-level `hubblestack-nova` folder?  or should the `.py` files live in a sub-folder under the `_modules` directory (e.g. `_modules/nova/`)

this approach would also support defining the CIS Level 2 checks.

**Comment by basepi** [comment]
@cedwards and I talked at length about these issues today. I think we're going to make it official that all nova modules will require accompanying yaml. For checks that don't actually require configuration (like the `pkgng_audit.py`), the yaml will basically just be a top-level key.

We're then going to move the yaml loading into hubble.py and add the ability to target by yaml file using hubble.audit.

All of these changes are building blocks to get us to the biggest change, which is the introduction of a topfile-like structure for targeting audits to minions. I plan to steal the topfile-parsing code so we can support all the match types. Basically, you'll be able to add audits to minions via yaml filename, with an optional tag filter.

Relevant issues: #68 #69

**Comment by dgmorrisjr** [comment]
how will that structure then allow for different profiles of inspections, such as CIS Level 1 vs CIS level 2, or STIG HML vs HMM vs MHL?  We you add additional Tags in the yaml for that further categorization?  I also think that this structure will be more difficult for review by security evaluators.  If the yaml files are organized in a way that is more consistent with they way the security standards are organized, it's easier for validation of coverage, etc...  it's organizing the profiles based on security users perspectives vs sw utility perspective.

**Comment by cedwards** [comment]
I had a discussion with @dgmorrisjr in Slack today. I think we're on the same page now. I'd like to see something like `benchmark-osfinger-level-(un)scored.yaml`. I think this aligns with how we want to be able to target these using the top-file idea.

**Comment by cedwards** [comment]
Initial work toward this restructuring is in #73.

**Comment by basepi** [comment]
Restructure: https://github.com/HubbleStack/Nova/pull/184
