### ISSUE TITLE
firewall policy audit module (iptables.check)

### ISSUE THREAD

**Issue by cedwards** [HubbleStack/Nova#48]
We should put together a firewall policy module that will ensure that certain firewall rules are applied. Initial support for `iptables`; eventual support for `pf`. This module could leverage `iptables.check` execution module.

```
firewall:
  whitelist:

    ssh:
      data:
        table: 'filter', 
        chain: None, 
        rule: '-p tcp --dport 22 -m state --state ESTABLISHED, RELATED -j ACCEPT' 
        family: 'ipv4'
```

**Comment by dgmorrisjr** [comment]
Would it also be possible to add a check for a the default policy, maybe using `iptables.get_policy` to help ensure they are all set to DROP

**Comment by cedwards** [comment]
Initial work for this (minus the default policy support) was completed in #99

**Comment by gmiu** [comment]
@dgmorrisjr, I'd like to hear more of your thoughts on using a default policy?

**Comment by dgmorrisjr** [comment]
security best practices is that we should set the default policy to "DROP", but really they can be set to the appropriate value for your organizationally defined value.   The DISA STIGs all specify that DROP is the appropriate value.  This helps reinforce a deny all traffic not explicitly listed type of policy.

in the iptables rules, they take the form of:

```
iptables -P <chain> <policy>
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP
```

I think the rule structure for hubblestack can closely match that of the salt states for iptables.set_policy, possibly something like this:

whitelist checks only...

```
firewall:
    verify_INPUT_default_policy:
      data:
        Red Hat Enterprise Linux Server-6:
        - default_policy:
            table:      filter
            chain:      INPUT
            policy:     DROP
            tag:        V-38383
      description:      (High) The default policy for the input filter table should be set to DROP
```

**Comment by basepi** [comment]
Does this issue need to remain open?

**Comment by gmiu** [comment]
@basepi, I'm currently working to support the true whitelist and the default policy in the new version of iptables.

**Comment by gmiu** [comment]
@cedwards, should we consider supporting `firewalld` also?

**Comment by gmiu** [comment]
Since the iptables modules does its job, I will close this and open a new one for the default policy and for the true whitelist.
