### ISSUE TITLE
Implement 'trigger` functionality

### ISSUE THREAD

**Issue by cedwards** [HubbleStack/Nova#52]
The idea behind the `trigger:` key is to allow automated remediation by way of states. In effect, if this check fails I want the system to apply a state to remediate the fix automagically.

Because all setups are different, the states will need to be created by the end-user and simply included in their state tree. The trigger, I imagine, would simply run `state.apply state` on the target system.

**Comment by basepi** [comment]
This issue was moved to hubblestack/hubble-salt#30
