### ISSUE TITLE
add ability to add args to grep statements

### ISSUE THREAD

**Issue by dgmorrisjr** [HubbleStack/Nova#55]
in `grep.py`, please add options parameter so that i can use the `-E` option for extended grep.  This would help check for 8.2 in the CIS file.   example command: `grep -E '(\\v|\\r|\\m|\\s)' /etc/issue`

Salt's `file.grep` option permits this as an optional parameter
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.file.html#salt.modules.file.grep

**Comment by dgmorrisjr** [comment]
I understand that `grep.py` is currently using `file.grep`.   and being able to use grep's options would add a lot of power to what `grep.py` can do today.    There are other inspections i'm running across that require the use of `egrep`.  So i'm thinking that the module for running arbitrary commands could be used for situations where the `egrep` statement are required.

**Comment by basepi** [comment]
Yeah, that will probably be the best route. But you'll be able to handle most of the grep stuff once I implement these arguments.
