### ISSUE TITLE
`hubble.audit` fails if a bad yaml file is located in the `hubblestack_nova` directory

### ISSUE THREAD

**Issue by gmiu** [HubbleStack/Nova#63]
`_get_yaml` function in each nova plugin will try to load all the yaml files in the `hubblestack_nova` directory. If at least one of the yaml files in there is having a bad yaml syntax, the `except` block will be reached and an empty dict will be returned. 

I'd suggest the `yaml.parser.ParserError` exception to be treated for each opened file.

**Comment by gmiu** [comment]
@basepi, any thoughts on this one? Should I put the error string in the log?

**Comment by basepi** [comment]
I think I'll take this one as part of #68. I'm going to move the yaml loading into hubble.py to allow for #69. I'll probably just report yaml loading errors in the output of the audit, under failures.

**Comment by cedwards** [comment]
Is this still relevant?

**Comment by basepi** [comment]
No. If an error occurs when loading yaml, it will be reported in the output of hubble.load
