### ISSUE TITLE
Adding hubblestack pillar data doesn't allow audits

### ISSUE THREAD

**Issue by SaltyCharles** [HubbleStack/Nova#75]
@basepi

```
# /srv/salt/pillar/hubble.sls
hubblestack.nova.dir: salt://hubblestack_nova
hubblestack.nova.saltenv: base
hubblestack.nova.autosync: True
hubblestack.nova.autoload: True
```

Using the above details in pillar prevented audits from working, resulting in the following:

```
salt \* hubble.audit
minion03:
    - False
    - No nova modules have been loaded.
```

Once the pillar was removed, sync and audit worked without issue.

**Comment by basepi** [comment]
I'm betting I made a mistake in my URL parsing for the nova dir. I'll look into this tomorrow.

Note, you can use triple backticks ``` to do multiline code blocks on github. I edited your post to use them, edit it yourself if you want to see how it's done.

**Comment by SaltyCharles** [comment]
Cool cool... I didn't even look at the preview

`shame`
