### ISSUE TITLE
Namespace profiles in return data

### ISSUE THREAD

**Issue by scottjpack** [HubbleStack/Nova#89]
When parsing the data into dashboards/reports it would be useful to have the profile that each check came from.   Something like the following:

```
{
  "return": {
    "profiles": [
      {
        "profile": "CIS-CentOS-6-L1-scored",
        "Success": [
          {
            "CIS-2.1.9": "Remove talk and talk-server"
          },
          {
            "CIS-2.1.2": "Remove telnet and telnet-server"
          }
        ],
        "Failure": [
          {
            "CIS-2.1.11": "Remove xinetd"
          },
          {
            "CIS-1.6.2": "Configure ExecShield (Scored)"
          }
        ]
      },
        {
        "profile": "org_custom",
        "Success": [
          {
            "ORG-SM1": "Don't do the bad thing"
          },
          {
            "ORG-SM2": "Don't do this other bad thing"
          }
        ],
        "Failure": [
          {
            "ORG-SM3": "There's this thing too"
          },
        ]
      }
    ]
  }
}
```

**Comment by basepi** [comment]
Hmmm. This hurts readability as a default setting. I may play with it a little and see if we can find something more readable, or make this config-gated.

I should also note this is actually a non-trivial change. The modules don't know the source of their checks as things stand. May be another fix that must be made across all the various modules.

**Comment by mew1033** [comment]
Fixed in https://github.com/HubbleStack/Nova/pull/197
?

**Comment by basepi** [comment]
Yep! Not sure why it didn't auto-close. Guess I forgot to add the "Fixes" line for auto-close.
